In [1]:
import pandas as pd
import pickle

In [17]:
df_clean = pd.read_csv("../data/test.txt") # <== Load you'r DF here
df_target = pd.read_csv("../data/train.txt") # <== Load you'r DF here

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1.0,1.0,0.0,0.0,0.0,5720,0,110.0,360.0,1.0,Urban
1,LP001022,1.0,1.0,1.0,0.0,0.0,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,1.0,1.0,2.0,0.0,0.0,5000,1800,208.0,360.0,1.0,Urban
4,LP001051,1.0,0.0,0.0,1.0,0.0,3276,0,78.0,360.0,1.0,Urban
5,LP001054,1.0,1.0,0.0,1.0,1.0,2165,3422,152.0,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
361,LP002969,1.0,1.0,1.0,0.0,0.0,2269,2167,99.0,360.0,1.0,Semiurban
362,LP002971,1.0,1.0,3.0,1.0,1.0,4009,1777,113.0,360.0,1.0,Urban
363,LP002975,1.0,1.0,0.0,0.0,0.0,4158,709,115.0,360.0,1.0,Urban
365,LP002986,1.0,1.0,0.0,0.0,0.0,5000,2393,158.0,360.0,1.0,Rural
366,LP002989,1.0,0.0,0.0,0.0,1.0,9200,0,98.0,180.0,1.0,Rural

In [14]:
df_clean= df_clean.dropna()
df_clean.info()

from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

df_clean['Gender'] = enc.fit_transform(df_clean[['Gender']])
df_clean['Self_Employed'] = enc.fit_transform(df_clean[['Self_Employed']])
df_clean['Education'] = enc.fit_transform(df_clean[['Education']])
df_clean['Dependents'] = enc.fit_transform(df_clean[['Dependents']])
df_clean['Married'] = enc.fit_transform(df_clean[['Married']])
df_OHEncoded = pd.get_dummies(columns = ['Property_Area'],data = df_clean)

df_OHEncoded

<class 'pandas.core.frame.DataFrame'>
Int64Index: 289 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            289 non-null    object
 1   Gender             289 non-null    float64
 2   Married            289 non-null    float64
 3   Dependents         289 non-null    float64
 4   Education          289 non-null    float64
 5   Self_Employed      289 non-null    float64
 6   ApplicantIncome    289 non-null    int64
 7   CoapplicantIncome  289 non-null    int64
 8   LoanAmount         289 non-null    float64
 9   Loan_Amount_Term   289 non-null    float64
 10  Credit_History     289 non-null    float64
 11  Property_Area      289 non-null    object
dtypes: float64(8), int64(2), object(2)
memory usage: 29.4+ KB

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001015,1.0,1.0,0.0,0.0,0.0,5720,0,110.0,360.0,1.0,0,0,1
1,LP001022,1.0,1.0,1.0,0.0,0.0,3076,1500,126.0,360.0,1.0,0,0,1
2,LP001031,1.0,1.0,2.0,0.0,0.0,5000,1800,208.0,360.0,1.0,0,0,1
4,LP001051,1.0,0.0,0.0,1.0,0.0,3276,0,78.0,360.0,1.0,0,0,1
5,LP001054,1.0,1.0,0.0,1.0,1.0,2165,3422,152.0,360.0,1.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,LP002969,1.0,1.0,1.0,0.0,0.0,2269,2167,99.0,360.0,1.0,0,1,0
362,LP002971,1.0,1.0,3.0,1.0,1.0,4009,1777,113.0,360.0,1.0,0,0,1
363,LP002975,1.0,1.0,0.0,0.0,0.0,4158,709,115.0,360.0,1.0,0,0,1
365,LP002986,1.0,1.0,0.0,0.0,0.0,5000,2393,158.0,360.0,1.0,1,0,0
366,LP002989,1.0,0.0,0.0,0.0,1.0,9200,0,98.0,180.0,1.0,1,0,0

In [15]:
pipe = pickle.load(open('../DATA/pipe_model_SGB.pkl', 'rb'))

In [30]:
from sklearn.metrics import classification_report
import numpy as np

X = df_OHEncoded.drop(['Loan_ID'],axis = 1)
y = df_target['Loan_Status']




y_pred = np.around(pipe.predict(X))

pipe.score(X,y)
# print(pipe.score(X,y))
# print('MAE =',mean_absolute_error(y,y_pred))
# # print('MSE =',mean_squared_error(y,y_pred)/16512)
# print('R2 =',r2_score(y,y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [614, 289]

In [24]:
y.shape

(614,)